/*
* generated by Xtext
*/
package at.ac.tuwien.big.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class QuestionnaireGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class QuestionnaireElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Questionnaire");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cQuestionnaireKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cQuotationMarkKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cQuotationMarkSpaceLeftSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cGroupsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cGroupsGroupParserRuleCall_4_0 = (RuleCall)cGroupsAssignment_4.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Questionnaire:
		//	"questionnaire" "\"" name=ID "\" [" groups+=Group+ "]";
		public ParserRule getRule() { return rule; }

		//"questionnaire" "\"" name=ID "\" [" groups+=Group+ "]"
		public Group getGroup() { return cGroup; }

		//"questionnaire"
		public Keyword getQuestionnaireKeyword_0() { return cQuestionnaireKeyword_0; }

		//"\""
		public Keyword getQuotationMarkKeyword_1() { return cQuotationMarkKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//"\" ["
		public Keyword getQuotationMarkSpaceLeftSquareBracketKeyword_3() { return cQuotationMarkSpaceLeftSquareBracketKeyword_3; }

		//groups+=Group+
		public Assignment getGroupsAssignment_4() { return cGroupsAssignment_4; }

		//Group
		public RuleCall getGroupsGroupParserRuleCall_4_0() { return cGroupsGroupParserRuleCall_4_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_5() { return cRightSquareBracketKeyword_5; }
	}

	public class GroupElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Group");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGroupKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cQuestionsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Alternatives cQuestionsAlternatives_3_0 = (Alternatives)cQuestionsAssignment_3.eContents().get(0);
		private final RuleCall cQuestionsOpenQuestionParserRuleCall_3_0_0 = (RuleCall)cQuestionsAlternatives_3_0.eContents().get(0);
		private final RuleCall cQuestionsClosedQuestionParserRuleCall_3_0_1 = (RuleCall)cQuestionsAlternatives_3_0.eContents().get(1);
		private final RuleCall cQuestionsLikertQuestionParserRuleCall_3_0_2 = (RuleCall)cQuestionsAlternatives_3_0.eContents().get(2);
		private final Keyword cRightSquareBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Group:
		//	"group" name=ID "[" questions+=(OpenQuestion | ClosedQuestion | LikertQuestion)+ "]" ","?;
		public ParserRule getRule() { return rule; }

		//"group" name=ID "[" questions+=(OpenQuestion | ClosedQuestion | LikertQuestion)+ "]" ","?
		public Group getGroup() { return cGroup; }

		//"group"
		public Keyword getGroupKeyword_0() { return cGroupKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"["
		public Keyword getLeftSquareBracketKeyword_2() { return cLeftSquareBracketKeyword_2; }

		//questions+=(OpenQuestion | ClosedQuestion | LikertQuestion)+
		public Assignment getQuestionsAssignment_3() { return cQuestionsAssignment_3; }

		//OpenQuestion | ClosedQuestion | LikertQuestion
		public Alternatives getQuestionsAlternatives_3_0() { return cQuestionsAlternatives_3_0; }

		//OpenQuestion
		public RuleCall getQuestionsOpenQuestionParserRuleCall_3_0_0() { return cQuestionsOpenQuestionParserRuleCall_3_0_0; }

		//ClosedQuestion
		public RuleCall getQuestionsClosedQuestionParserRuleCall_3_0_1() { return cQuestionsClosedQuestionParserRuleCall_3_0_1; }

		//LikertQuestion
		public RuleCall getQuestionsLikertQuestionParserRuleCall_3_0_2() { return cQuestionsLikertQuestionParserRuleCall_3_0_2; }

		//"]"
		public Keyword getRightSquareBracketKeyword_4() { return cRightSquareBracketKeyword_4; }

		//","?
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }
	}

	public class OpenQuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "OpenQuestion");
		private final UnorderedGroup cUnorderedGroup = (UnorderedGroup)rule.eContents().get(1);
		private final Assignment cMandatoryAssignment_0 = (Assignment)cUnorderedGroup.eContents().get(0);
		private final Keyword cMandatoryMandatoryKeyword_0_0 = (Keyword)cMandatoryAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cUnorderedGroup.eContents().get(1);
		private final Assignment cMultilineAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final Keyword cMultilineMultilineKeyword_1_0_0 = (Keyword)cMultilineAssignment_1_0.eContents().get(0);
		private final Keyword cOpenQuestionKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cQuestionAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cQuestionIDTerminalRuleCall_1_2_0 = (RuleCall)cQuestionAssignment_1_2.eContents().get(0);
		private final Keyword cCommaKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		
		//OpenQuestion:
		//	mandatory?="mandatory" & multiline?="multiline"? "open question" question=ID ","?;
		public ParserRule getRule() { return rule; }

		//mandatory?="mandatory" & multiline?="multiline"? "open question" question=ID ","?
		public UnorderedGroup getUnorderedGroup() { return cUnorderedGroup; }

		//mandatory?="mandatory"
		public Assignment getMandatoryAssignment_0() { return cMandatoryAssignment_0; }

		//"mandatory"
		public Keyword getMandatoryMandatoryKeyword_0_0() { return cMandatoryMandatoryKeyword_0_0; }

		//multiline?="multiline"? "open question" question=ID ","?
		public Group getGroup_1() { return cGroup_1; }

		//multiline?="multiline"?
		public Assignment getMultilineAssignment_1_0() { return cMultilineAssignment_1_0; }

		//"multiline"
		public Keyword getMultilineMultilineKeyword_1_0_0() { return cMultilineMultilineKeyword_1_0_0; }

		//"open question"
		public Keyword getOpenQuestionKeyword_1_1() { return cOpenQuestionKeyword_1_1; }

		//question=ID
		public Assignment getQuestionAssignment_1_2() { return cQuestionAssignment_1_2; }

		//ID
		public RuleCall getQuestionIDTerminalRuleCall_1_2_0() { return cQuestionIDTerminalRuleCall_1_2_0; }

		//","?
		public Keyword getCommaKeyword_1_3() { return cCommaKeyword_1_3; }
	}

	public class ClosedQuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ClosedQuestion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cClosedQuestionAllowingKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cSingleAnswerKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Keyword cMultipleAnswersKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Assignment cQuestionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cQuestionIDTerminalRuleCall_2_0 = (RuleCall)cQuestionAssignment_2.eContents().get(0);
		private final Assignment cAnswersAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAnswersAnswersParserRuleCall_3_0 = (RuleCall)cAnswersAssignment_3.eContents().get(0);
		
		//ClosedQuestion:
		//	"closed question allowing" ("single answer" | "multiple answers") question=ID answers=Answers;
		public ParserRule getRule() { return rule; }

		//"closed question allowing" ("single answer" | "multiple answers") question=ID answers=Answers
		public Group getGroup() { return cGroup; }

		//"closed question allowing"
		public Keyword getClosedQuestionAllowingKeyword_0() { return cClosedQuestionAllowingKeyword_0; }

		//"single answer" | "multiple answers"
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//"single answer"
		public Keyword getSingleAnswerKeyword_1_0() { return cSingleAnswerKeyword_1_0; }

		//"multiple answers"
		public Keyword getMultipleAnswersKeyword_1_1() { return cMultipleAnswersKeyword_1_1; }

		//question=ID
		public Assignment getQuestionAssignment_2() { return cQuestionAssignment_2; }

		//ID
		public RuleCall getQuestionIDTerminalRuleCall_2_0() { return cQuestionIDTerminalRuleCall_2_0; }

		//answers=Answers
		public Assignment getAnswersAssignment_3() { return cAnswersAssignment_3; }

		//Answers
		public RuleCall getAnswersAnswersParserRuleCall_3_0() { return cAnswersAnswersParserRuleCall_3_0; }
	}

	public class LikertQuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "LikertQuestion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLikertQuestionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cQuestionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cQuestionIDTerminalRuleCall_1_0 = (RuleCall)cQuestionAssignment_1.eContents().get(0);
		private final Keyword cLeftParenthesisHyphenMinusKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLowerAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLowerINTTerminalRuleCall_3_0 = (RuleCall)cLowerAssignment_3.eContents().get(0);
		private final Keyword cFullStopFullStopKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cHigherAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cHigherINTTerminalRuleCall_5_0 = (RuleCall)cHigherAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//LikertQuestion:
		//	"likert question" question=ID "(-" lower=INT ".." higher=INT ")";
		public ParserRule getRule() { return rule; }

		//"likert question" question=ID "(-" lower=INT ".." higher=INT ")"
		public Group getGroup() { return cGroup; }

		//"likert question"
		public Keyword getLikertQuestionKeyword_0() { return cLikertQuestionKeyword_0; }

		//question=ID
		public Assignment getQuestionAssignment_1() { return cQuestionAssignment_1; }

		//ID
		public RuleCall getQuestionIDTerminalRuleCall_1_0() { return cQuestionIDTerminalRuleCall_1_0; }

		//"(-"
		public Keyword getLeftParenthesisHyphenMinusKeyword_2() { return cLeftParenthesisHyphenMinusKeyword_2; }

		//lower=INT
		public Assignment getLowerAssignment_3() { return cLowerAssignment_3; }

		//INT
		public RuleCall getLowerINTTerminalRuleCall_3_0() { return cLowerINTTerminalRuleCall_3_0; }

		//".."
		public Keyword getFullStopFullStopKeyword_4() { return cFullStopFullStopKeyword_4; }

		//higher=INT
		public Assignment getHigherAssignment_5() { return cHigherAssignment_5; }

		//INT
		public RuleCall getHigherINTTerminalRuleCall_5_0() { return cHigherINTTerminalRuleCall_5_0; }

		//")"
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
	}

	public class AnswersElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Answers");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAnswersKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cAnswersAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Alternatives cAnswersAlternatives_1_0 = (Alternatives)cAnswersAssignment_1.eContents().get(0);
		private final RuleCall cAnswersOpenAnswerParserRuleCall_1_0_0 = (RuleCall)cAnswersAlternatives_1_0.eContents().get(0);
		private final RuleCall cAnswersClosedAnswerParserRuleCall_1_0_1 = (RuleCall)cAnswersAlternatives_1_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDefaultAnswerIsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cAnswerAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cAnswerClosedAnswerCrossReference_3_1_0 = (CrossReference)cAnswerAssignment_3_1.eContents().get(0);
		private final RuleCall cAnswerClosedAnswerIDTerminalRuleCall_3_1_0_1 = (RuleCall)cAnswerClosedAnswerCrossReference_3_1_0.eContents().get(1);
		
		//Answers:
		//	"answers [" answers+=(OpenAnswer | ClosedAnswer)+ "]" ("default answer is" answer=[ClosedAnswer])?;
		public ParserRule getRule() { return rule; }

		//"answers [" answers+=(OpenAnswer | ClosedAnswer)+ "]" ("default answer is" answer=[ClosedAnswer])?
		public Group getGroup() { return cGroup; }

		//"answers ["
		public Keyword getAnswersKeyword_0() { return cAnswersKeyword_0; }

		//answers+=(OpenAnswer | ClosedAnswer)+
		public Assignment getAnswersAssignment_1() { return cAnswersAssignment_1; }

		//OpenAnswer | ClosedAnswer
		public Alternatives getAnswersAlternatives_1_0() { return cAnswersAlternatives_1_0; }

		//OpenAnswer
		public RuleCall getAnswersOpenAnswerParserRuleCall_1_0_0() { return cAnswersOpenAnswerParserRuleCall_1_0_0; }

		//ClosedAnswer
		public RuleCall getAnswersClosedAnswerParserRuleCall_1_0_1() { return cAnswersClosedAnswerParserRuleCall_1_0_1; }

		//"]"
		public Keyword getRightSquareBracketKeyword_2() { return cRightSquareBracketKeyword_2; }

		//("default answer is" answer=[ClosedAnswer])?
		public Group getGroup_3() { return cGroup_3; }

		//"default answer is"
		public Keyword getDefaultAnswerIsKeyword_3_0() { return cDefaultAnswerIsKeyword_3_0; }

		//answer=[ClosedAnswer]
		public Assignment getAnswerAssignment_3_1() { return cAnswerAssignment_3_1; }

		//[ClosedAnswer]
		public CrossReference getAnswerClosedAnswerCrossReference_3_1_0() { return cAnswerClosedAnswerCrossReference_3_1_0; }

		//ID
		public RuleCall getAnswerClosedAnswerIDTerminalRuleCall_3_1_0_1() { return cAnswerClosedAnswerIDTerminalRuleCall_3_1_0_1; }
	}

	public class OpenAnswerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "OpenAnswer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cAnswerAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cAnswerIDTerminalRuleCall_0_0 = (RuleCall)cAnswerAssignment_0.eContents().get(0);
		private final Keyword cFullStopFullStopFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//OpenAnswer:
		//	answer=ID "..." ","?;
		public ParserRule getRule() { return rule; }

		//answer=ID "..." ","?
		public Group getGroup() { return cGroup; }

		//answer=ID
		public Assignment getAnswerAssignment_0() { return cAnswerAssignment_0; }

		//ID
		public RuleCall getAnswerIDTerminalRuleCall_0_0() { return cAnswerIDTerminalRuleCall_0_0; }

		//"..."
		public Keyword getFullStopFullStopFullStopKeyword_1() { return cFullStopFullStopFullStopKeyword_1; }

		//","?
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }
	}

	public class ClosedAnswerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ClosedAnswer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cAnswerAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cAnswerIDTerminalRuleCall_0_0 = (RuleCall)cAnswerAssignment_0.eContents().get(0);
		private final Keyword cCommaKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cEnablesQuestionKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cQuestionAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cQuestionClosedQuestionCrossReference_2_1_0 = (CrossReference)cQuestionAssignment_2_1.eContents().get(0);
		private final RuleCall cQuestionClosedQuestionIDTerminalRuleCall_2_1_0_1 = (RuleCall)cQuestionClosedQuestionCrossReference_2_1_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//ClosedAnswer:
		//	answer=ID ","? ("enables question [" question=[ClosedQuestion] "]")? ","?;
		public ParserRule getRule() { return rule; }

		//answer=ID ","? ("enables question [" question=[ClosedQuestion] "]")? ","?
		public Group getGroup() { return cGroup; }

		//answer=ID
		public Assignment getAnswerAssignment_0() { return cAnswerAssignment_0; }

		//ID
		public RuleCall getAnswerIDTerminalRuleCall_0_0() { return cAnswerIDTerminalRuleCall_0_0; }

		//","?
		public Keyword getCommaKeyword_1() { return cCommaKeyword_1; }

		//("enables question [" question=[ClosedQuestion] "]")?
		public Group getGroup_2() { return cGroup_2; }

		//"enables question ["
		public Keyword getEnablesQuestionKeyword_2_0() { return cEnablesQuestionKeyword_2_0; }

		//question=[ClosedQuestion]
		public Assignment getQuestionAssignment_2_1() { return cQuestionAssignment_2_1; }

		//[ClosedQuestion]
		public CrossReference getQuestionClosedQuestionCrossReference_2_1_0() { return cQuestionClosedQuestionCrossReference_2_1_0; }

		//ID
		public RuleCall getQuestionClosedQuestionIDTerminalRuleCall_2_1_0_1() { return cQuestionClosedQuestionIDTerminalRuleCall_2_1_0_1; }

		//"]"
		public Keyword getRightSquareBracketKeyword_2_2() { return cRightSquareBracketKeyword_2_2; }

		//","?
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }
	}
	
	
	private QuestionnaireElements pQuestionnaire;
	private GroupElements pGroup;
	private OpenQuestionElements pOpenQuestion;
	private ClosedQuestionElements pClosedQuestion;
	private LikertQuestionElements pLikertQuestion;
	private AnswersElements pAnswers;
	private OpenAnswerElements pOpenAnswer;
	private ClosedAnswerElements pClosedAnswer;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public QuestionnaireGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("at.ac.tuwien.big.Questionnaire".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Questionnaire:
	//	"questionnaire" "\"" name=ID "\" [" groups+=Group+ "]";
	public QuestionnaireElements getQuestionnaireAccess() {
		return (pQuestionnaire != null) ? pQuestionnaire : (pQuestionnaire = new QuestionnaireElements());
	}
	
	public ParserRule getQuestionnaireRule() {
		return getQuestionnaireAccess().getRule();
	}

	//Group:
	//	"group" name=ID "[" questions+=(OpenQuestion | ClosedQuestion | LikertQuestion)+ "]" ","?;
	public GroupElements getGroupAccess() {
		return (pGroup != null) ? pGroup : (pGroup = new GroupElements());
	}
	
	public ParserRule getGroupRule() {
		return getGroupAccess().getRule();
	}

	//OpenQuestion:
	//	mandatory?="mandatory" & multiline?="multiline"? "open question" question=ID ","?;
	public OpenQuestionElements getOpenQuestionAccess() {
		return (pOpenQuestion != null) ? pOpenQuestion : (pOpenQuestion = new OpenQuestionElements());
	}
	
	public ParserRule getOpenQuestionRule() {
		return getOpenQuestionAccess().getRule();
	}

	//ClosedQuestion:
	//	"closed question allowing" ("single answer" | "multiple answers") question=ID answers=Answers;
	public ClosedQuestionElements getClosedQuestionAccess() {
		return (pClosedQuestion != null) ? pClosedQuestion : (pClosedQuestion = new ClosedQuestionElements());
	}
	
	public ParserRule getClosedQuestionRule() {
		return getClosedQuestionAccess().getRule();
	}

	//LikertQuestion:
	//	"likert question" question=ID "(-" lower=INT ".." higher=INT ")";
	public LikertQuestionElements getLikertQuestionAccess() {
		return (pLikertQuestion != null) ? pLikertQuestion : (pLikertQuestion = new LikertQuestionElements());
	}
	
	public ParserRule getLikertQuestionRule() {
		return getLikertQuestionAccess().getRule();
	}

	//Answers:
	//	"answers [" answers+=(OpenAnswer | ClosedAnswer)+ "]" ("default answer is" answer=[ClosedAnswer])?;
	public AnswersElements getAnswersAccess() {
		return (pAnswers != null) ? pAnswers : (pAnswers = new AnswersElements());
	}
	
	public ParserRule getAnswersRule() {
		return getAnswersAccess().getRule();
	}

	//OpenAnswer:
	//	answer=ID "..." ","?;
	public OpenAnswerElements getOpenAnswerAccess() {
		return (pOpenAnswer != null) ? pOpenAnswer : (pOpenAnswer = new OpenAnswerElements());
	}
	
	public ParserRule getOpenAnswerRule() {
		return getOpenAnswerAccess().getRule();
	}

	//ClosedAnswer:
	//	answer=ID ","? ("enables question [" question=[ClosedQuestion] "]")? ","?;
	public ClosedAnswerElements getClosedAnswerAccess() {
		return (pClosedAnswer != null) ? pClosedAnswer : (pClosedAnswer = new ClosedAnswerElements());
	}
	
	public ParserRule getClosedAnswerRule() {
		return getClosedAnswerAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
