/**
 * generated by Xtext
 */
package at.ac.tuwien.big.validation;

import at.ac.tuwien.big.validation.AbstractQuestionnaireValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class QuestionnaireValidator extends AbstractQuestionnaireValidator {
}
