/*
 * generated by Xtext
 */
package at.ac.tuwien.big.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractQuestionnaireValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(at.ac.tuwien.big.questionnaire.QuestionnairePackage.eINSTANCE);
		return result;
	}
}
