/*
* generated by Xtext
*/
package at.ac.tuwien.big.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.ac.tuwien.big.services.QuestionnaireGrammarAccess;

public class QuestionnaireParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private QuestionnaireGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected at.ac.tuwien.big.parser.antlr.internal.InternalQuestionnaireParser createParser(XtextTokenStream stream) {
		return new at.ac.tuwien.big.parser.antlr.internal.InternalQuestionnaireParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Questionnaire";
	}
	
	public QuestionnaireGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(QuestionnaireGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
