/*
* generated by Xtext
*/
package at.ac.tuwien.big;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class QuestionnaireStandaloneSetup extends QuestionnaireStandaloneSetupGenerated{

	public static void doSetup() {
		new QuestionnaireStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

