/*
 * generated by Xtext
 */
package at.ac.tuwien.big;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class QuestionnaireRuntimeModule extends at.ac.tuwien.big.AbstractQuestionnaireRuntimeModule {

}
